version: 0.0
os: linux
files:
  - source: /app/
    destination: /opt/office
permissions:
  - object: /
    pattern: "**"
    owner: perinei
    group: perinei
hooks:
  ApplicationStop:
    - location: scripts/1_ApplicationStop.sh
      timeout: 60
      runas: perinei
  BeforeInstall:
    - location: scripts/2_BeforeInstall.sh
      timeout: 180
      runas: perinei
  AfterInstall:
    - location: scripts/3_AfterInstall.sh
      timeout: 300
      runas: perinei
  ApplicationStart:
    - location: scripts/4_ApplicationStart.sh
      timeout: 60
      runas: perinei
  ValidateService:
    - location: scripts/5_ValidateService.sh
      timeout: 60
      runas: perinei
